CREATE TYPE regularity AS ENUM ('weekly', 'biweekly', 'monthly');

CREATE TABLE openmic (
  id            SERIAL,
  name      text,
  regularity   regularity not null,
  comedian      boolean not null,
  poet          boolean not null,
  musician      boolean not null,
  contact_email_address   text,
  contact_phone_number   text,
  venue_name   text,
  venue_address   text not null,
  state   text not null,
  city   text not null,
  sign_up_time   text not null,
  start_time   text not null,
  is_free      boolean not null,
  next_openmic_date date not null,
  notes   text,
  website text,
  deletion_requests integer default 0,
  monday  boolean not null default false,
  tuesday  boolean not null default false,
  wednesday  boolean not null default false,
  thursday  boolean not null default false,
  friday  boolean not null default false,
  saturday  boolean not null default false,
  sunday  boolean not null default false,
  PRIMARY KEY(name, venue_name, venue_address)
);